config/routes.rb
Rails.application.routes.draw do
  resources :caminhos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "page/:id" => "page#index", :as => :page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caminho.rb
class Caminho < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/caminhos_controller.rb
class CaminhosController < ApplicationController
  before_action :set_caminho, only: [:show, :edit, :update, :destroy]

  # GET /caminhos
  # GET /caminhos.json
  def index
    @caminhos = Caminho.all
  end

  # GET /caminhos/1
  # GET /caminhos/1.json
  def show
  end

  # GET /caminhos/new
  def new
    @caminho = Caminho.new
  end

  # GET /caminhos/1/edit
  def edit
  end

  # POST /caminhos
  # POST /caminhos.json
  def create
    @caminho = Caminho.new(caminho_params)

    respond_to do |format|
      if @caminho.save
        format.html { redirect_to @caminho, notice: 'Caminho was successfully created.' }
        format.json { render :show, status: :created, location: @caminho }
      else
        format.html { render :new }
        format.json { render json: @caminho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caminhos/1
  # PATCH/PUT /caminhos/1.json
  def update
    respond_to do |format|
      if @caminho.update(caminho_params)
        format.html { redirect_to @caminho, notice: 'Caminho was successfully updated.' }
        format.json { render :show, status: :ok, location: @caminho }
      else
        format.html { render :edit }
        format.json { render json: @caminho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caminhos/1
  # DELETE /caminhos/1.json
  def destroy
    @caminho.destroy
    respond_to do |format|
      format.html { redirect_to caminhos_url, notice: 'Caminho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caminho
      @caminho = Caminho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caminho_params
      params.fetch(:caminho, {})
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    if params[:id] && template_exists?(params[:id], ["page"])
      render params[:id]
    else
      redirect_to '/404.html', :status => 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caminhos_helper.rb
module CaminhosHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/caminhos/_form.html.erb
<%= form_with(model: caminho, local: true) do |form| %>
  <% if caminho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caminho.errors.count, "error") %> prohibited this caminho from being saved:</h2>

      <ul>
      <% caminho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/caminhos/edit.html.erb
<h1>Editing Caminho</h1>

<%= render 'form', caminho: @caminho %>

<%= link_to 'Show', @caminho %> |
<%= link_to 'Back', caminhos_path %>

app/views/caminhos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caminhos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  <style>
    /* Always set the map height explicitly to define the size of the div
     * element that contains the map. */
    #map {
      height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
  </style>
  </thead>

  <tbody>
		<div id="map"></div>
		  <script>
		    // Note: This example requires that you consent to location sharing when
		    // prompted by your browser. If you see the error "The Geolocation service
		    // failed.", it means you probably did not give permission for the browser to
		    // locate you.
		    var map, infoWindow;
		    function initMap() {
		      map = new google.maps.Map(document.getElementById('map'), {
		        center: {lat: -34.397, lng: 150.644},
		        zoom: 6
		      });
		      infoWindow = new google.maps.InfoWindow;

		      // Try HTML5 geolocation.
		      if (navigator.geolocation) {
		        navigator.geolocation.getCurrentPosition(function(position) {
		          var pos = {
		            lat: position.coords.latitude,
		            lng: position.coords.longitude
		          };

		          infoWindow.setPosition(pos);
		          infoWindow.setContent('Location found.');
		          infoWindow.open(map);
		          map.setCenter(pos);
		        }, function() {
		          handleLocationError(true, infoWindow, map.getCenter());
		        });
		      } else {
		        // Browser doesn't support Geolocation
		        handleLocationError(false, infoWindow, map.getCenter());
		      }
		    }

		    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
		      infoWindow.setPosition(pos);
		      infoWindow.setContent(browserHasGeolocation ?
		                            'Error: The Geolocation service failed.' :
		                            'Error: Your browser doesn\'t support geolocation.');
		      infoWindow.open(map);
		    }
		  </script>
		  <script async defer
		  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCM7wHnTHhwOyy9FlLkdgwfyNRNu5Ucrck&callback=initMap">
		  </script>	




    <% @caminhos.each do |caminho| %>
      <tr>
        <td><%= link_to 'Show', caminho %></td>
        <td><%= link_to 'Edit', edit_caminho_path(caminho) %></td>
        <td><%= link_to 'Destroy', caminho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caminho', new_caminho_path %>

app/views/caminhos/new.html.erb
<h1>New Caminho</h1>

<%= render 'form', caminho: @caminho %>

<%= link_to 'Back', caminhos_path %>

app/views/caminhos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_caminho_path(@caminho) %> |
<%= link_to 'Back', caminhos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Map</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/distance.html.erb
  <thead>
    <style>
      #right-panel {
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }

      #right-panel select, #right-panel input {
        font-size: 15px;
      }

      #right-panel select {
        width: 100%;
      }

      #right-panel i {
        font-size: 12px;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
        width: 50%;
      }
      #right-panel {
        float: right;
        width: 48%;
        padding-left: 2%;
      }
      #output {
        font-size: 11px;
      }
    </style>
  </thead>
  <tbody>
    <div id="right-panel">
      <div>
        <strong>Results</strong>
      </div>
      <div id="output"></div>
    </div>
    <div id="map"></div>
    <script>
      function fazAcontecer(map, service, origin1, destinationA, geocoder, bounds, markersArray, destinationIcon, originIcon){
        service.getDistanceMatrix({
          origins: [origin1],
          destinations: [destinationA],
          travelMode: 'DRIVING',
          unitSystem: google.maps.UnitSystem.METRIC,
          avoidHighways: false,
          avoidTolls: false
        }, function(response, status) {
          if (status !== 'OK') {
            alert('Error was: ' + status);
          } else {
            var originList = response.originAddresses;
            var destinationList = response.destinationAddresses;
            var outputDiv = document.getElementById('output');
            outputDiv.innerHTML = '';
            deleteMarkers(markersArray);

            var showGeocodedAddressOnMap = function(asDestination) {
              var icon = asDestination ? destinationIcon : originIcon;
              return function(results, status) {
                if (status === 'OK') {
                  map.fitBounds(bounds.extend(results[0].geometry.location));
                  markersArray.push(new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location,
                    icon: icon
                  }));
                } else {
                  alert('Geocode was not successful due to: ' + status);
                }
              };
            };

            for (var i = 0; i < originList.length; i++) {
              var results = response.rows[i].elements;
              geocoder.geocode({'address': originList[i]},
                  showGeocodedAddressOnMap(false));
              for (var j = 0; j < results.length; j++) {
                geocoder.geocode({'address': destinationList[j]},
                    showGeocodedAddressOnMap(true));
                outputDiv.innerHTML += originList[i] + ' até ' + destinationList[j] +
                    ': ' + results[j].distance.text + ' em ' + //results[j].sistance.text é a distancia
                    results[j].duration.text + '<br>';
              }
            }
          }
        });
      };


      function initMap() {
        var bounds = new google.maps.LatLngBounds;
        var markersArray = [];

        var infoWindow = new google.maps.InfoWindow;
        var origin1 = {lat: 55.930, lng: -3.118}; //para colocar lat/long var origin1 = {lat: 55.930, lng: -3.118};
        var destinationA = 'São Carlos, centro SP';

        var destinationIcon = 'https://chart.googleapis.com/chart?' +
            'chst=d_map_pin_letter&chld=D|FF0000|000000';
        var originIcon = 'https://chart.googleapis.com/chart?' +
            'chst=d_map_pin_letter&chld=O|FFFF00|000000';
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 55.930, lng: -3.118},
          zoom: 10
        });

        var geocoder = new google.maps.Geocoder;
        var service = new google.maps.DistanceMatrixService;
        if (navigator.geolocation) {
		        navigator.geolocation.getCurrentPosition(function(position) {
		          var pos = {
		            lat: position.coords.latitude,
		            lng: position.coords.longitude
		          };
              origin1 = pos;
              fazAcontecer(map, service, origin1, destinationA, geocoder, bounds, markersArray, destinationIcon, originIcon);
              
		          
		        });
		      } else {
		        // Browser doesn't support Geolocation
		        fazAcontecer(map, service, origin1, destinationA, geocoder, bounds, markersArray, destinationIcon, originIcon);
		      }
      }

      function deleteMarkers(markersArray) {
        for (var i = 0; i < markersArray.length; i++) {
          markersArray[i].setMap(null);
        }
        markersArray = [];
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCM7wHnTHhwOyy9FlLkdgwfyNRNu5Ucrck&callback=initMap">
    </script>
  </tbody>

app/views/page/heatmap.html.erb
<thead>
  <meta charset="utf-8">
  <title>Mapa de calor</title>
  <style>
    /* Always set the map height explicitly to define the size of the div
     * element that contains the map. */
    #map {
      height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
  </style>
</thead>
<tbody>
  <div id="map"></div>
  <script>
    var map;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 2,
        center: {lat: -33.865427, lng: 151.196123},
        mapTypeId: 'terrain'
      });

      // Create a <script> tag and set the USGS URL as the source.
      var script = document.createElement('script');

      // This example uses a local copy of the GeoJSON stored at
      // http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojsonp
      script.src = 'https://developers.google.com/maps/documentation/javascript/examples/json/earthquake_GeoJSONP.js';
      document.getElementsByTagName('head')[0].appendChild(script);

      map.data.setStyle(function(feature) {
        var magnitude = feature.getProperty('mag');
        return {
          icon: getCircle(magnitude)
        };
      });
    }

    function getCircle(magnitude) {
      return {
        path: google.maps.SymbolPath.CIRCLE,
        fillColor: 'red',
        fillOpacity: .2,
        scale: Math.pow(2, magnitude) / 2,
        strokeColor: 'white',
        strokeWeight: .5
      };
    }

    function eqfeed_callback(results) {
      map.data.addGeoJson(results);
    }
  </script>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCM7wHnTHhwOyy9FlLkdgwfyNRNu5Ucrck&callback=initMap">
  </script>
</tbody>

app/views/page/loc.html.erb
<table>
  <thead>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <style>
    /* Always set the map height explicitly to define the size of the div
     * element that contains the map. */
    #map {
      height: 100%;
			
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
  </style>
  </thead>

  <tbody>
		<div id="map"></div>
		  <script>
		    // Note: This example requires that you consent to location sharing when
		    // prompted by your browser. If you see the error "The Geolocation service
		    // failed.", it means you probably did not give permission for the browser to
		    // locate you.
		    var map, infoWindow;
		    function initMap() {
		      map = new google.maps.Map(document.getElementById('map'), {
		        center: {lat: -34.397, lng: 150.644},
		        zoom: 6
		      });
		      infoWindow = new google.maps.InfoWindow;

		      // Try HTML5 geolocation.
		      if (navigator.geolocation) {
		        navigator.geolocation.getCurrentPosition(function(position) {
		          var pos = {
		            lat: position.coords.latitude,
		            lng: position.coords.longitude
		          };

		          infoWindow.setPosition(pos);
		          infoWindow.setContent('Location found.');
		          infoWindow.open(map);
		          map.setCenter(pos);
		        }, function() {
		          handleLocationError(true, infoWindow, map.getCenter());
		        });
		      } else {
		        // Browser doesn't support Geolocation
		        handleLocationError(false, infoWindow, map.getCenter());
		      }
		    }

		    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
		      infoWindow.setPosition(pos);
		      infoWindow.setContent(browserHasGeolocation ?
		                            'Error: The Geolocation service failed.' :
		                            'Error: Your browser doesn\'t support geolocation.');
		      infoWindow.open(map);
		    }
		  </script>
		  <script async defer
		  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCM7wHnTHhwOyy9FlLkdgwfyNRNu5Ucrck&callback=initMap">
		  </script>	
  </tbody>
</table>

app/views/page/route.html.erb
<thead>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <title>routes</title>
  <style>
    /* Always set the map height explicitly to define the size of the div
      * element that contains the map. */
    #map {
      height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    #floating-panel {
      position: absolute;
      top: 10px;
      left: 25%;
      z-index: 5;
      background-color: #fff;
      padding: 5px;
      border: 1px solid #999;
      text-align: center;
      font-family: 'Roboto','sans-serif';
      line-height: 30px;
      padding-left: 10px;
    }
    #right-panel {
      font-family: 'Roboto','sans-serif';
      line-height: 30px;
      padding-left: 10px;
    }

    #right-panel select, #right-panel input {
      font-size: 15px;
    }

    #right-panel select {
      width: 100%;
    }

    #right-panel i {
      font-size: 12px;
    }
    #right-panel {
      height: 100%;
      float: right;
      width: 390px;
      overflow: auto;
    }
    #map {
      margin-right: 400px;
    }
    #floating-panel {
      background: #fff;
      padding: 5px;
      font-size: 14px;
      font-family: Arial;
      border: 1px solid #ccc;
      box-shadow: 0 2px 2px rgba(33, 33, 33, 0.4);
      display: none;
    }
    @media print {
      #map {
        height: 500px;
        margin: 0;
      }
      #right-panel {
        float: none;
        width: auto;
      }
    }
  </style>
</thead>
<tbody>
  <div id="floating-panel">
    <strong>Start:</strong>
    <select id="start">
      <option value="Bauru, Brasil">Bauru</option>
      <option value="São Carlos, Brasil">São Carlos</option>
    </select>
    <br>
    <strong>End:</strong>
    <select id="end">
      <option value="São Carlos, Brasil">São Carlos</option>
      <option value="Bauru, Brasil">Bauru</option>
    </select>
  </div>
  <div id="right-panel"></div>
  <div id="map"></div>
  <script>
    function initMap() {
      var directionsDisplay = new google.maps.DirectionsRenderer;
      var directionsService = new google.maps.DirectionsService;
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 7,
        center: 'Bauru, Brasil'
      });
      directionsDisplay.setMap(map);
     // directionsDisplay.set
      directionsDisplay.setPanel(document.getElementById('right-panel'));

      var control = document.getElementById('floating-panel');
      control.style.display = 'block';
      map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);

      calculateAndDisplayRoute(directionsService, directionsDisplay);
      var onChangeHandler = function() {
        calculateAndDisplayRoute(directionsService, directionsDisplay);
      };
      document.getElementById('start').addEventListener('change', onChangeHandler);
      document.getElementById('end').addEventListener('change', onChangeHandler);
    }

    function calculateAndDisplayRoute(directionsService, directionsDisplay) {
      var start = document.getElementById('start').value;
      var end = document.getElementById('end').value;
      directionsService.route({
        origin: start,
        destination: end,
        travelMode: 'DRIVING'
      }, function(response, status) {
        if (status === 'OK') {
          directionsDisplay.setDirections(response);
        } else {
          window.alert('Directions request failed due to ' + status);
        }
      });
    }
  </script>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCM7wHnTHhwOyy9FlLkdgwfyNRNu5Ucrck&callback=initMap">
  </script>
</tbody>